jobs:
    main:
        image: golang:latest
        steps:
            - print: echo this is shared-steps test main job
            - sd_step: sd-step exec core/node "node -v"
            - sd_step_tilde: | 
                    #sd-step exec --pkg-version "22.17.0" core/node "node -v"
                    ls -lrt
                    #sd-step exec --pkg-version "~22.17.0" core/node "node -v"
            - sd_step_hat: sd-step exec --pkg-version "^6.0.0" core/node "node -v"
            - sd_step_specify: sd-step exec --pkg-version "4.2.6" core/node "node -v"
        requires:
            - ~pr
            - ~commit
