jobs:
    main:
        image: golang:latest
        steps:
            - print: echo this is shared-steps test main job && sleep 1000
            - sd_step: sd-step exec core/node "node -v"
            - sd_step_tilde: sd-step exec --pkg-version "~6.11.3" core/node "node -v"
            - sd_step_hat: sd-step exec --pkg-version "^6.0.0" core/node "node -v"
            - sd_step_specify: sd-step exec --pkg-version "4.2.6" core/node "node -v"
        requires:
            - ~pr
            - ~commit
